# Generated by Django 5.2.15 on 2026-06-16 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslettercampaign',
            name='preview_text',
            field=models.CharField(blank=True, help_text='Short preview text shown in email clients after the subject line.', max_length=255),
        ),
    ]
