# Generated by Django 5.2.15 on 2026-06-19 05:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, help_text='Short bio about yourself.')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('role', models.CharField(choices=[('reader', 'Reader'), ('contributor', 'Contributor')], default='reader', max_length=20)),
                ('website', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True, help_text='Your GitHub profile URL.', null=True)),
                ('twitter_url', models.URLField(blank=True, help_text='Your Twitter/X profile URL.', null=True)),
                ('linkedin_url', models.URLField(blank=True, help_text='Your LinkedIn profile URL.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
