# Generated by Django 5.2.15 on 2026-06-19 05:27

import django.db.models.deletion
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('learning_objectives', django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='What will learners achieve in this chapter?')),
                ('estimated_hours', models.DecimalField(decimal_places=1, default=0.0, help_text='Estimated hours to complete the chapter.', max_digits=4)),
                ('meta_title', models.CharField(blank=True, help_text='SEO page title (max 60 chars). Auto-generated when blank.', max_length=60)),
                ('meta_description', models.CharField(blank=True, help_text='SEO meta description (max 160 chars). Uses chapter description when blank.', max_length=160)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('icon_html', models.TextField(default='<i class="fa-solid fa-book"></i>', help_text='Full HTML icon. E.g. <code>&lt;i class="fa-brands fa-python"&gt;&lt;/i&gt;</code> or an inline SVG.')),
                ('image', models.ImageField(blank=True, null=True, upload_to='topics/')),
                ('image_alt', models.CharField(blank=True, help_text='Alt text for the topic image.', max_length=255)),
                ('meta_title', models.CharField(blank=True, help_text='SEO page title (max 60 chars). Auto-generated when blank.', max_length=60)),
                ('meta_description', models.CharField(blank=True, help_text='SEO meta description (max 160 chars). Uses topic description when blank.', max_length=160)),
                ('featured', models.BooleanField(default=False, help_text='Show in the Featured Topics section on the homepage.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order on the topics listing page')),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('summary', models.TextField()),
                ('content', django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Full lesson content. Use CKEditor 5 to add headings, images, links, lists, tables, and more.')),
                ('video_url', models.URLField(blank=True, help_text='Optional video URL (e.g. YouTube/Vimeo) for the lesson.')),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', help_text='Difficulty level displayed to learners.', max_length=15)),
                ('meta_title', models.CharField(blank=True, help_text='SEO page title (max 60 chars). Auto-generated when blank.', max_length=60)),
                ('meta_description', models.CharField(blank=True, help_text='SEO meta description (max 160 chars). Uses lesson summary when blank.', max_length=160)),
                ('featured', models.BooleanField(default=False, help_text='Show in the Featured / Popular Lessons section on the homepage.')),
                ('order', models.PositiveIntegerField(default=0)),
                ('reading_time', models.PositiveIntegerField(default=5, help_text='Estimated reading time in minutes')),
                ('is_published', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending Review'), ('published', 'Published'), ('rejected', 'Rejected')], default='published', help_text='Lesson publication status.', max_length=20)),
                ('rejection_note', models.TextField(blank=True, help_text='Admin note explaining why this lesson was rejected.')),
                ('published_at', models.DateTimeField(blank=True, help_text='When the lesson was published.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='learning.chapter')),
                ('submitted_by', models.ForeignKey(blank=True, help_text='The contributor who submitted this lesson.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_lessons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.AddField(
            model_name='chapter',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='learning.topic'),
        ),
        migrations.CreateModel(
            name='LessonBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='learning.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lesson Bookmark',
                'verbose_name_plural': 'Lesson Bookmarks',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'lesson')},
            },
        ),
        migrations.CreateModel(
            name='RecentlyViewed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recent_views', to='learning.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recently_viewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recently Viewed',
                'verbose_name_plural': 'Recently Viewed',
                'ordering': ['-viewed_at'],
                'unique_together': {('user', 'lesson')},
            },
        ),
        migrations.CreateModel(
            name='UserLessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress_pct', models.PositiveIntegerField(default=0, help_text='Reading progress 0–100%')),
                ('last_viewed', models.DateTimeField(auto_now=True)),
                ('is_complete', models.BooleanField(default=False)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='learning.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lesson Progress',
                'verbose_name_plural': 'Lesson Progress',
                'unique_together': {('user', 'lesson')},
            },
        ),
    ]
