# Generated by Django 5.2.15 on 2026-06-19 09:42

import django.db.models.deletion
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_lessoncomment_commentreply_certificate_lessonrating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='estimated_hours',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='learning_objectives',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='meta_description',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='meta_title',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='difficulty',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=15),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='meta_description',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='meta_title',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='reading_time',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='rejection_note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending Review'), ('published', 'Published'), ('rejected', 'Rejected')], default='published', max_length=20),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_lessons', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='topic',
            name='image_alt',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='topic',
            name='meta_description',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AlterField(
            model_name='topic',
            name='meta_title',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='topic',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userlessonprogress',
            name='progress_pct',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notif_type', models.CharField(choices=[('lesson_approved', 'Lesson Approved'), ('lesson_rejected', 'Lesson Rejected'), ('new_comment', 'New Comment'), ('certificate_earned', 'Certificate Earned'), ('quiz_passed', 'Quiz Passed'), ('topic_proposal_approved', 'Topic Proposal Approved'), ('topic_proposal_rejected', 'Topic Proposal Rejected')], max_length=40)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('url', models.CharField(blank=True, max_length=500)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TopicProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='What should this topic cover? Who is the audience?')),
                ('icon_html', models.CharField(default='<i class="fa-solid fa-book"></i>', help_text='Optional HTML icon snippet.', max_length=300)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('rejection_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_topic', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_proposal', to='learning.topic')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_proposals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Topic Proposal',
                'verbose_name_plural': 'Topic Proposals',
                'ordering': ['-created_at'],
            },
        ),
    ]
