# Generated by Django 5.2.15 on 2026-06-20 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0006_topic_status_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('lesson_approved', 'Lesson Approved'), ('lesson_rejected', 'Lesson Rejected'), ('new_comment', 'New Comment'), ('certificate_earned', 'Certificate Earned'), ('quiz_passed', 'Quiz Passed'), ('topic_proposal_approved', 'Topic Proposal Approved'), ('topic_proposal_rejected', 'Topic Proposal Rejected'), ('topic_review_submitted', 'Topic Review Submitted'), ('topic_published', 'Topic Published'), ('topic_changes_requested', 'Topic Changes Requested'), ('topic_rejected_to_draft', 'Topic Rejected to Draft')], max_length=40),
        ),
    ]
