# Generated by Django 5.1.4 on 2026-06-20 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0003_lesson_published_at_lesson_rejection_note_and_more"),
        ("learning", "0007_alter_notification_notif_type"),
    ]

    operations = []
