# Generated by Django 5.1.4 on 2026-06-21 10:36

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0008_merge_20260620_1155"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lesson",
            name="submitted_by",
        ),
        migrations.AlterField(
            model_name="chapter",
            name="estimated_hours",
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=4),
        ),
        migrations.AlterField(
            model_name="chapter",
            name="learning_objectives",
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True),
        ),
        migrations.AlterField(
            model_name="chapter",
            name="meta_description",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AlterField(
            model_name="chapter",
            name="meta_title",
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="published_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="rejection_note",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="status",
            field=models.CharField(
                choices=[("draft", "Draft"), ("published", "Published")],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="video_url",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="topic",
            name="image_alt",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="userlessonprogress",
            name="progress_pct",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
