# Generated by Django 5.2.15 on 2026-06-21 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0009_remove_lesson_submitted_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='required_quiz_questions',
            field=models.PositiveIntegerField(blank=True, help_text='Number of random quiz questions required for lesson completion. Leave empty to allow normal completion. Set a number to require passing a quiz before completion.', null=True),
        ),
    ]
